### ISSUE TITLE
Design our own theme to replace JNews

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/stanforddaily-website#49]
Currently, the Stanford Daily's website is using a child theme based on the [JNews](https://jnews.io/) theme.

However, there are several problems with this current approach. For example:
- The website, especially the admin panel, is very slow due to the high resources usage of the JNews theme.
- The website is still using JNews 2, while the newest version is JNews 3. However, due to the changes made in the child theme, it is hard to update the theme.

Given the fact that the authors rarely use the advanced features in JNews, it might be feasible for us to write a new theme for the Daily website.

Followings are some tasks that need to be done:
- [ ] Design the layout and design of the theme (discuss with the Graphics Team?)
  - [ ] Header & footer
  - [ ] Sidebar
  - [ ] **Home page #65**
  - [x] Single article
     - [ ] Possible different design for news, opinions, and magazine post #83
  - [ ] Single page
  - [ ] Archive page
     - [ ] Category page #105 
     - [ ] Tag page
     - [x] Search page
     - [x] Author page
- [ ] Responsive design
- [x] Find a starter theme to work on (possibly https://github.com/milohuang/reverie or https://underscores.me/ or https://roots.io/sage/ or https://github.com/understrap/understrap or https://foundationpress.olefredrik.com/?)
  - **We are using https://underscores.me/**
  - Should we use Bootstrap or other library?
  - Should we use css or sass or less?
  - Edit directly on starter theme or use a child theme?
- [ ] Override all the JNews shortcodes with our own implementation, that way we can have a graceful migration and won’t need to change the content
- [ ] Check if any post is using JNews-specific features
  - [x] Each post's "subtitle"
    - **We are using https://github.com/benhuson/wp-subtitle**
    - **#50**
  - [ ] Feature image size
    - https://github.com/TheStanfordDaily/stanforddaily-website/blob/master/wp-content/themes/jnews/class/Image/Image.php?
- Additional features
  - [ ] Related articles #66 
  - [ ] View counts
  - [ ] Social media sharing buttons in the article page #67 
  - [x] Add CSS prefix to support old browsers #68 
  - [ ] Add footer nav menu #75 
  - [ ] Make the front page more dynamic #78 
  - [ ] **Add ads #72**
  - [ ] "Posted x hours ago" feature for date #88

**Comment by epicfaace** [comment]
- Also need to make sure the theme supports co-authors plus: https://vip.wordpress.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/

**Comment by hesyifei** [comment]
>     * Also need to make sure the theme supports co-authors plus: https://vip.wordpress.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/

It's already supported right now! 😄 https://github.com/TheStanfordDaily/stanforddaily-website/blob/custom-theme/wp-content/themes/thestanforddaily/inc/template-tags.php

**Comment by epicfaace** [comment]
Closing this because we have a lot of issues covering all these points.
